name: CREATOR workflow CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: read-all

jobs:
  creator-checker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - run: npm run build --if-present
    - run: npm run test-creator-node
    
  build-creator-cl:    
    name: Build creator_cl Docker Image
    needs: creator-checker

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU        
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx        
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Package Registry        
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build & Push Docker image
      run: docker buildx build -t ghcr.io/${{ github.repository_owner }}/creator_cl -f ./dockers/command_line/Dockerfile  --push --platform=linux/arm64,linux/amd64 .
